### ISSUE TITLE
Meteor 1.3.2.2 with Modulus@6.0.0

### ISSUE THREAD

**Issue by flean** [onmodulus/modulus-cli#110]
```
Compressing project...
7.3 MB written
Uploading project...
Upload progress [===================] 100%
Deploying project into Meteor runtime...
 
[✓] bundle running at xxxxxxx.onmodulus.net
```
Nothing happens, it just does that. No provisioning or building environment...

**Comment by ajschmaltz** [comment]
Yup...  and now I'm stuck.  meteor --version 1.3.2 doesn't seem to actually downgrade.  Has anyone found a solution?

**Comment by ajschmaltz** [comment]
@flean  Try npm init and tell me what happens

**Comment by harlanj** [comment]
The `meteor build` command uses the `--server-only` flag. That flag only works with `meteor@v1.3.x`. One solution is to upgrade your application to use any Meteor version 1.3 or greater. 

The other solution is to update your runtime to Node and use any version of the cli 5.x and below.

@flean Sorry for the trouble. However, this issue is with the actual build image. I created an issue on the [build image repo](https://github.com/onmodulus/docker-build-meteor/issues/15) that you can track.

**Comment by flean** [comment]
@harlanj Thanks, hope they can fix this. Lately, modulus has been making it really difficult to deploy. Last time when 1.3 came out I was in limbo for a week until the build image added the ```--server-only``` that I required.

**Comment by flean** [comment]
It's working now
