### ISSUE TITLE
No longer is possible to select node version

### ISSUE THREAD

**Issue by ernestorocha** [onmodulus/modulus-cli#43]
When I deploy and try to select a node version this happens:

```
$ modulus deploy -n 0.10.36 -p project
Welcome to Modulus
You are logged in as ernestorocha
Selecting project
```

And later on the output:
```
INFO: Found package.json file: /package.json
INFO: Node version specified in package.json: 0.10.33
INFO: Initializing Node v0.10.33
```

Any idea ?

**Comment by fiveisprime** [comment]
That is correct. Demeteorizer was updated to use the node version specified in
boot.js rather than accepting the version option. The option in the Moduus CLI
needs to be removed or demeteorizer needs to accept an override (again).

You can open an issue on [demeteorizer](https://github.com/onmodulus/demeteorizer/issues) for this.
