### ISSUE TITLE
error: bitpay is not compatible with architecture 'os.linux.x86_64'

### ISSUE THREAD

**Issue by yogiben** [onmodulus/modulus-cli#58]
Not sure which part of the stack this is.

```
Meteor project detected...

WARNING: The output directory is under your source tree.

Errors prevented bundling:
While linking the program:
error: bitpay is not compatible with architecture 'os.linux.x86_64'

undefined
[Error] Error: Conversion failed.
```

**Comment by fiveisprime** [comment]
This is due to a limitation of the meteorhacks npm package where compiled
modules cannot be rebuilt for specific architectures. For now, you'll need to
downgrade to `modulus@4.0.2` by running `$ npm install -g modulus@4.0.2` or
remove the compiled module.

I also suggest commenting on [this issue](https://github.com/meteorhacks/npm/issues/40) as it's been a problem for a while now.
